### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#66]
With pegasus 0.17.2, I can run `pegasus demuxEM`. (This command is not recognized in the latest GitHub version, see #65).

However, the command throws an error:

```
$   pegasus demuxEM -p 4 --generate-diagnostic-plots batch4_5p_adt_hto.csv.gz raw_feature_bc_matrix.h5 $output_name
2020-07-12 19:35:02,778 - pegasus - INFO - Time spent on 'read_input' = 1.81s.
ADT file is loaded.
2020-07-12 19:35:04,576 - pegasus - INFO - Time spent on 'read_input' = 1.80s.
RNA file is loaded.
/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/pegasus/demuxEM/demuxEM.py:38: RuntimeWarning:

divide by zero encountered in log10

Traceback (most recent call last):
  File "/Users/kamil/miniconda3/envs/pegasus2/bin/pegasus", line 8, in <module>
    sys.exit(main())
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/pegasus/__main__.py", line 65, in main
    command.execute()
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/pegasus/commands/DemuxEM.py", line 64, in execute
    **kwargs
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/pegasus/pipeline/demuxEM_pipeline.py", line 25, in run_demuxEM_pipeline
    demuxEM.estimate_background_probs(adt, random_state=kwargs["random_state"])
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/pegasus/demuxEM/demuxEM.py", line 39, in estimate_background_probs
    kmeans = KMeans(n_clusters=2, random_state=random_state).fit(counts_log10)
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 994, in fit
    accept_large_sparse=False)
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/sklearn/utils/validation.py", line 646, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/kamil/miniconda3/envs/pegasus2/lib/python3.7/site-packages/sklearn/utils/validation.py", line 100, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

```

Here is the csv:

```
$ gzip -cd batch4_5p_adt_hto.csv.gz | head -n3 | cut -f1-5 -d,
Antibody,AAACCTGAGAAACCAT,AAACCTGAGAAACCGC,AAACCTGAGAAACCTA,AAACCTGAGAAACGAG
HT_C0251,0,2,0,0
HT_C0252,0,293,0,0
```

**Comment by slowkow** [comment]
After changing `np.log10(x)` to `np.log10(1 + x)` (as described here https://github.com/klarman-cell-observatory/demuxEM/pull/3), the command works without errors.

It seems like the results might be reasonable.

```r
h5_file <- "data/batch_1-4_5p/data_output/batch4_5p_rna/demuxEM_demux.h5sc"

x <- rhdf5::h5read(h5_file, "/GRCh38/_barcodes") %>%
  as_tibble

x %>% filter(demux_type == "singlet") %>% count(assignment)
```

```
# A tibble: 8 x 2
  assignment     n
  <chr>      <int>
1 HT_C0251     206
2 HT_C0252     872
3 HT_C0254     529
4 HT_C0256     279
5 HT_C0257    1054
6 HT_C0258     197
7 HT_C0259     723
8 HT_C0260     834

```

**Comment by slowkow** [comment]
The result above was run on `filtered_bc_matrix.h5` without errors.

When I tried running on `raw_bc_matrix.h5` instead, then I got this error:

```
RuntimeWarning: invalid value encountered in true_divide
```

I was able to eliminate this error by changing line 59 of `demuxEM.py`:

```python
# No error
probs_mle = arr / (arr.sum() + 1)

# Error
probs_mle = arr / arr.sum()
```

**Comment by bli25** [comment]
@slowkow  I believe the latest pegasus should address this issue?
